// @ts-nocheck
// v0.9 화면 렌더링 계층(레거시 이관). 판정 로직은 src/diagnosis(Rule Engine)만 사용한다.
// Phase 1 원칙: 화면 문구·흐름은 v0.9 그대로, 점수는 엔진 결과만 표시.
import {
  evaluate, activeQuestions, deepQuestions, profile as engineProfile, evidenceLevel,
  band as engineBand, nextTrlGate, ANCHORS, EVIDENCE, CORE,
} from '../diagnosis';
import { strategicOptions as engineStrategicOptions, riskItems as engineRiskItems } from '../diagnosis/strategy';
import { roadmapCandidates as engineRoadmapCandidates, otherFieldCandidates, loadRoadmapIndex, ROADMAP_GROUPS } from '../roadmap/candidates';
import options from './options.json';
import { versionLabel } from '../build-info';
import { buildReportViewModel, ISSUER, reportId as vmReportId } from '../reports/report-model';

const { STEPS, BUSINESS_TYPES, STAGES, SIZES, YEARS } = options;
const fmtScore = (v) => (v === null || v === undefined ? '판단 보류' : `${Math.round(v)}/100`);
const capText = (v) => (v === null || v === undefined ? '판단 보류(응답 부족)' : `${engineBand(v)}(${Math.round(v)}/100)`);
const STORAGE_KEY="beconic_tgn_v09";
function fresh(){return {step:0,visited:[0],mode:"quick",entry:"no-data",company:{name:"",stage:"소기업",roadmapField:"AI",bizType:"AI/SW 중심",sectorDetail:"",size:"1~9명",years:"1~3년",techKnow:"부분적으로 알고 있음",product:"",customer:""},discovery:{hardPart:"",automated:"",data:"",external:"",people:"",validation:""},inventory:[],answers:{},evidence:{},results:null}}
let state=fresh();
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
const cname=c=>({tech:"기술성숙",rd:"R&D 역량",exec:"실행준비",evidence:"기술기록",scale:"확장준비",strategy:"전략정렬",risk:"리스크 대응"})[c]||c;
const profile=()=>engineProfile(state.company.bizType);
const deepQs=()=>deepQuestions(state.company.bizType);
const activeQs=()=>activeQuestions(state.mode,state.company.bizType);
function roadmapSelect(){return `<select id="roadmapField">${Object.entries(ROADMAP_GROUPS).map(([g,a])=>`<optgroup label="${g}">${a.map(x=>`<option ${x===state.company.roadmapField?"selected":""}>${x}</option>`).join("")}</optgroup>`).join("")}</select>`}
function seedInv(){if(state.inventory.length)return;let p=profile(),x=p==="제조"||p==="융합"?[["제품 설계·사양","설계기술"],["핵심 생산·공정","공정기술"],["품질검사·판정","품질기술"],["설비·장비/제어","생산기술"]]:p==="딥테크"?[["핵심 원리·원천기술","원천기술"],["시제품·실험 시스템","실증기술"],["핵심 소재·부품/알고리즘","핵심기술"],["Scale-up·적용기술","응용기술"]]:p==="서비스"?[["핵심 서비스 제공방식","서비스기술"],["운영 프로세스","운영기술"],["데이터 활용","데이터기술"],["외부 플랫폼 연계","통합기술"]]:[["제품/서비스 구현","응용기술"],["데이터 활용","데이터기술"],["AI·알고리즘/노하우","핵심기술"],["외부 솔루션 연계","통합기술"]];state.inventory=x.map((a,n)=>({id:n+1,name:a[0],type:a[1],ownership:"확인필요",status:"추정",critical:n<2,trl:0,confirmed:false}))}
function syncBasic(){if(!$("companyName"))return;state.company={name:$("companyName").value.trim(),stage:$("companyStage").value,roadmapField:$("roadmapField").value,bizType:$("bizType").value,sectorDetail:$("sectorDetail").value.trim(),size:$("companySize").value,years:$("companyYears").value,techKnow:$("techKnow").value,product:$("product").value.trim(),customer:$("customer").value.trim()}}
function syncDiscovery(){["hardPart","automated","data","external","people","validation"].forEach(k=>{let e=$("d_"+k);if(e)state.discovery[k]=e.value.trim()})}
function navTo(n){if(state.step===0)syncBasic();if(state.step===1)syncDiscovery();state.step=Math.max(0,Math.min(5,Number(n)));if(!state.visited.includes(state.step))state.visited.push(state.step);if(state.step>=2)seedInv();if(state.step===5)calc();render();window.scrollTo({top:0,behavior:"smooth"})}
function nav(){$("nav").innerHTML=STEPS.map((m,i)=>`<button class="navstep ${state.step===i?"active":""} ${state.visited.includes(i)&&i!==state.step?"visited":""}" onclick="navTo(${i})"><span class="num">${state.visited.includes(i)&&i<state.step?"✓":i+1}</span><span><strong>${m[0]}</strong><small>${m[1]}</small></span></button>`).join("");let p=Math.round(state.step/5*100);$("progBar").style.width=p+"%";$("progTxt").textContent=p+"%";$("heroStep").textContent=STEPS[state.step][0];$("heroSub").textContent=STEPS[state.step][1]}
function field(l,x){return `<div class="field"><label>${l}</label>${x}</div>`}
const EXAMPLE_BANK={};
function exampleBox(id,text){EXAMPLE_BANK[id]=text;return `<div class="example-box"><div class="example-head"><b>작성 예시</b><button type="button" class="example-use" onclick="applyExample('${id}')">예시 입력</button></div><div class="example-text">${esc(text)}</div><div class="example-note">※ 예시는 참고용입니다. 자사 상황·수치·고객·기술명에 맞게 수정해 주세요.</div></div>`}
function fieldExample(l,x,id,example){return `<div class="field"><label>${l}</label>${x}${exampleBox(id,example)}</div>`}
function applyExample(id){let el=$(id),text=EXAMPLE_BANK[id];if(!el||!text)return;el.value=text;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));el.focus()}
function sel(id,a,v){return `<select id="${id}">${a.map(x=>`<option ${x===v?"selected":""}>${x}</option>`).join("")}</select>`}
function basic(){$("s0").innerHTML=`<div class="panel"><h2>1. 기업 이해</h2><p class="desc">기업규모와 기술로드맵 분야를 분리해 입력합니다. 산업분류와 운영유형을 분리한 이유는 같은 산업에서도 SW·제조·서비스형 진단문항이 달라지기 때문입니다.</p><div class="choice-row" style="margin-bottom:16px"><button class="choice ${state.entry==="no-data"?"active":""}" onclick="setEntry('no-data')">자료 없이 시작</button><button class="choice ${state.entry==="with-data"?"active":""}" onclick="setEntry('with-data')">자료와 함께 정밀진단</button><button class="choice ${state.entry==="delegate"?"active":""}" onclick="setEntry('delegate')">담당자 확인 중심</button></div><div class="grid two">${field("기업명",`<input id="companyName" value="${esc(state.company.name)}" placeholder="예: 비코닉랩">`)}${field("기업 단계",sel("companyStage",STAGES,state.company.stage))}${field("기술로드맵 기준 분야",roadmapSelect())}${field("기업 운영유형",sel("bizType",BUSINESS_TYPES,state.company.bizType))}${fieldExample("세부 업종·기술분야",`<input id="sectorDetail" value="${esc(state.company.sectorDetail)}" placeholder="예: 산업용 설비 예지보전 AI SaaS">`,"sectorDetail","산업용 제조설비 예지보전 AI SaaS / 제조 데이터 분석·이상탐지 솔루션")}${field("인원 규모",sel("companySize",SIZES,state.company.size))}${field("업력",sel("companyYears",YEARS,state.company.years))}${field("대표자의 자사 기술 이해도",sel("techKnow",["잘 알고 있음","부분적으로 알고 있음","거의 모름","담당자 확인 필요"],state.company.techKnow))}</div><div class="grid two" style="margin-top:13px">${fieldExample("주요 제품·서비스",`<textarea id="product" placeholder="제품·서비스가 무엇을 하고 어떤 결과를 제공하는지 적어주세요.">${esc(state.company.product)}</textarea>`,"product","제조설비의 진동·온도·전류 센서 데이터를 분석해 이상징후와 고장 가능성을 조기에 알려주는 AI 기반 예지보전 SaaS입니다. 설비별 상태를 대시보드로 보여주고 정비 우선순위를 추천합니다.")}${fieldExample("주요 고객·사용자",`<textarea id="customer" placeholder="누가 사용하며 어떤 문제를 해결하려는지 적어주세요.">${esc(state.company.customer)}</textarea>`,"customer","자동차·전자부품 등 중소 제조기업의 공장장, 생산기술팀, 설비보전팀이 주요 사용자입니다. 비계획 설비정지, 잦은 고장, 유지보수 비용 증가 문제를 줄이기 위해 사용합니다.")}</div><div class="notice"><b>Red Team 개선:</b> 기업단계·직원수·업력은 기술역량 점수에 직접 가산하지 않고, 기대수준과 해석문구를 조정하는 맥락변수로만 사용합니다. 규모가 크다고 기술점수가 자동으로 높아지지 않습니다.</div><h3 style="margin-top:16px">사용법 · 활용법</h3><div class="usage-guide"><div class="usage-step"><b>1. 사업언어로 입력</b><p>전문기술명을 몰라도 제품·고객·문제·현장 경험을 적으면 됩니다.</p></div><div class="usage-step"><b>2. 핵심기술 확인</b><p>자동 생성된 기술후보 중 사업성과를 좌우하는 기술만 핵심으로 지정합니다.</p></div><div class="usage-step"><b>3. 결과를 실행에 활용</b><p>진단결과를 R&D 계획, 기술문서, 지원사업 준비, 내부 회의, 멘토링에 사용합니다.</p></div></div><div class="usage-callout"><b>권장 활용:</b> 1차 자가진단 → CTO/기술담당자 확인 → 필요한 Evidence 보완 → 90일 실행 → 재진단. 처음부터 모든 자료를 준비할 필요는 없습니다.</div><div class="actions"><span></span><button class="btn primary" onclick="navTo(1)">기술 발견 시작 →</button></div></div>`}
function setEntry(v){syncBasic();state.entry=v;basic()}
const DISCOVERY_EXAMPLES={
 hardPart:"설비별로 형식이 다른 센서 데이터를 표준화하고, 고장 직전의 미세한 패턴을 학습해 오탐을 줄이는 이상탐지 알고리즘과 현장 튜닝 노하우가 가장 따라 하기 어렵습니다.",
 automated:"작업자가 엑셀과 경험으로 판단하던 설비 이상 여부를 시스템이 실시간으로 탐지하고, 위험도와 정비 우선순위까지 자동 추천합니다.",
 data:"1초 단위 진동·온도·전류 센서값, 설비 알람 로그, 고장·정비 이력, 생산량·불량률 데이터가 지속적으로 쌓입니다.",
 external:"AWS 클라우드, Anthropic/OpenAI 등 LLM API, 센서 게이트웨이 공급사, 일부 데이터 수집 모듈 외주개발에 의존합니다.",
 people:"CTO 1명, AI 개발자 2명, 백엔드 개발자 1명, 제조현장 적용을 담당하는 생산기술 PM 1명이 기술을 가장 잘 이해하고 있습니다.",
 validation:"A전자와 B부품 2개 공장에서 약 3개월간 PoC를 진행했으며, 주요 고장 유형 4종에 대해 사전 탐지 성능과 오탐률을 검증했습니다. 현재는 장기 운영 데이터가 더 필요합니다."
};
function discField(k,l,p){return fieldExample(l,`<textarea id="d_${k}" placeholder="${p}">${esc(state.discovery[k])}</textarea>`,`d_${k}`,DISCOVERY_EXAMPLES[k]||"")}
function discovery(){$("s1").innerHTML=`<div class="panel"><h2>2. Technology Discovery</h2><p class="desc">대표자가 기술명을 몰라도 답할 수 있는 질문으로 기술 후보를 역추적합니다. 각 주관식 문항에는 실제 작성 수준을 이해할 수 있도록 일관된 샘플기업 기준의 작성 예시를 넣었습니다.</p><div class="grid two">${discField("hardPart","경쟁사가 따라 하기 가장 어려운 부분","제품설계, 공정, 데이터, 알고리즘, 노하우 등")}${discField("automated","사람 대신 자동으로 판단·처리되는 부분","예측, 추천, 검사, 제어, 품질판정 등")}${discField("data","계속 쌓이는 데이터","고객, 생산, 센서, 이미지, 로그, 거래 등")}${discField("external","외부에 의존하는 부분","외주개발, LLM API, 클라우드, 장비, 공급사 등")}${discField("people","기술을 가장 잘 아는 사람","CTO, 개발자, 생산책임자, 연구소장, 외주사 등")}${discField("validation","외부에서 실제 확인된 경험","PoC, 판매, 납품, 시험, 인증, 특허 등")}</div><div class="notice"><b>작성 팁:</b> 가능한 경우 “무엇을·누가·어디서·얼마나·어떤 결과로”까지 적어주세요. 수치와 기간, 실제 고객·현장 검증 여부가 포함되면 진단 정확도가 높아집니다.</div><div class="actions"><button class="btn" onclick="navTo(0)">← 이전</button><button class="btn primary" onclick="makeInv()">기술 후보 생성 →</button></div></div>`}
function makeInv(){syncDiscovery();state.inventory=[];seedInv();if(state.discovery.hardPart)state.inventory.unshift({id:99,name:state.discovery.hardPart,type:"핵심 차별기술 후보",ownership:"자체 가능",status:"대표진술",critical:true,trl:0,confirmed:false});navTo(2)}
function inlineSel(a,v,on){return `<select onchange="${on}">${a.map(x=>`<option ${x===v?"selected":""}>${x}</option>`).join("")}</select>`}
function trlSel(v,on){return `<select onchange="${on}"><option value="0" ${!v?"selected":""}>TRL 확인필요</option><option value="2" ${v===2?"selected":""}>TRL 1~2 · 원리/개념</option><option value="4" ${v===4?"selected":""}>TRL 3~4 · PoC/실험</option><option value="6" ${v===6?"selected":""}>TRL 5~6 · 시제품/유사환경</option><option value="7" ${v===7?"selected":""}>TRL 7 · 실제환경 실증</option><option value="8" ${v===8?"selected":""}>TRL 8 · 시스템 완성</option><option value="9" ${v===9?"selected":""}>TRL 9 · 실사용/양산</option></select>`}
function inv(){seedInv();$("s2").innerHTML=`<div class="panel"><h2>3. 핵심기술 식별</h2><p class="desc">기업 전체에 TRL 하나를 붙이지 않고, 사업성과와 제품성능을 좌우하는 핵심기술별로 현재 수준을 확인합니다.</p><div class="tech-list">${state.inventory.map((t,i)=>`<div class="tech-row"><div class="tech-title"><b>${esc(t.name)}</b><small>${esc(t.type)}</small><label class="check"><input type="checkbox" ${t.critical?"checked":""} onchange="setInv(${i},'critical',this.checked)"> 핵심기술</label></div>${inlineSel(["자체","외부","혼합","확인필요","자체 가능"],t.ownership,`setInv(${i},'ownership',this.value)`)}${inlineSel(["확정","대표진술","추정","미확인"],t.status,`setInv(${i},'status',this.value)`)}${trlSel(t.trl,`setInv(${i},'trl',Number(this.value))`)}<button class="btn ${t.confirmed?"soft":""}" onclick="toggleInv(${i})">${t.confirmed?"✓ 확인":"내용 확인"}</button></div>`).join("")}</div><div class="notice"><b>핵심 원칙:</b> TRL은 기술성숙도이고, 회사규모·매출·시장성·증빙신뢰도와 분리합니다.</div><div class="actions"><button class="btn" onclick="navTo(1)">← 이전</button><button class="btn primary" onclick="navTo(3)">핵심진단 →</button></div></div>`}
function setInv(i,k,v){state.inventory[i][k]=v}function toggleInv(i){state.inventory[i].confirmed=!state.inventory[i].confirmed;inv()}
function qhtml(q,i){let a=ANCHORS[q.cat];return `<div class="q"><div class="qhead"><div class="qtitle">${i+1}. ${q.t}</div><div class="qmeta">${cname(q.cat)}${q.critical?" · 핵심":""}</div></div><div class="scale5">${a.map((x,n)=>`<button class="${state.answers[q.id]===n+1?"selected":""}" onclick="ans('${q.id}',${n+1})"><b>${n+1}</b><br>${x}</button>`).join("")}</div><div class="unknown-row"><span class="hint">현재 상태와 가장 가까운 행동·운영 수준을 선택하세요.</span><button class="unknown ${state.answers[q.id]===null?"selected":""}" onclick="ans('${q.id}',null)">? 모름·확인필요</button></div></div>`}
function diagnosis(){let qs=activeQs(),core=qs.filter(q=>q.id[0]==="q"),deep=qs.filter(q=>q.id[0]==="d");$("s3").innerHTML=`<div class="panel"><h2>4. 핵심진단</h2><p class="desc">기본 12문항으로 먼저 진단하고 필요한 경우에만 기업 운영유형에 맞는 심화문항을 추가합니다.</p><div class="choice-row" style="margin-bottom:14px"><button class="choice ${state.mode==="quick"?"active":""}" onclick="setMode('quick')">간편 · 12문항</button><button class="choice ${state.mode==="deep"?"active":""}" onclick="setMode('deep')">정밀 · ${12+deepQs().length}문항</button></div><div class="module-head"><h3>공통 핵심진단</h3><span>기술·R&D·실행·확장·전략·리스크</span></div><div class="qwrap">${core.map((q,i)=>qhtml(q,i)).join("")}</div>${state.mode==="deep"&&deep.length?`<div class="module-head"><h3>${esc(state.company.bizType)} 심화</h3><span>선택형</span></div><div class="qwrap">${deep.map((q,i)=>qhtml(q,core.length+i)).join("")}</div>`:""}<div class="notice">“모름”은 0점이 아닙니다. 미확인 상태로 남기고 근거확인·진단신뢰도에 반영합니다.</div><div class="actions"><button class="btn" onclick="navTo(2)">← 이전</button><button class="btn primary" onclick="navTo(4)">근거 확인 →</button></div></div>`}
function setMode(v){state.mode=v;diagnosis()}function ans(id,v){state.answers[id]=v;diagnosis()}
const ev=id=>evidenceLevel(state.evidence,id);
function answerLabel(q){let v=state.answers[q.id];return v===null||v===undefined?"모름·확인필요":ANCHORS[q.cat][v-1]}
function evidenceReason(q){let v=state.answers[q.id];if(v===null||v===undefined)return "모름·확인필요";if(q.critical)return "핵심판단 검증";if(v>=4)return "높은 자기평가 검증";return "선별 확인"}
function evidenceCandidates(){let qs=activeQs();return qs.filter(q=>{let v=state.answers[q.id];return q.critical||v===null||v===undefined||v>=4}).sort((a,b)=>{let av=(state.answers[a.id]===null||state.answers[a.id]===undefined)?3:(a.critical?2:1),bv=(state.answers[b.id]===null||state.answers[b.id]===undefined)?3:(b.critical?2:1);return bv-av}).slice(0,6)}
function evidence(){let qs=evidenceCandidates();$("s4").innerHTML=`<div class="panel"><h2>5. 근거 확인</h2><p class="desc">이 단계는 기술점수를 다시 매기는 단계가 아니라, <b>현재 판단을 얼마나 믿을 수 있는지 확인하는 단계</b>입니다. 최대 6개 핵심 항목만 확인합니다.</p><div class="evidence-help"><div class="mini"><strong>“모름·확인필요”의 뜻</strong><p>기술이 없다는 뜻이 아닙니다. 현재 응답자가 판단할 정보가 부족하다는 뜻입니다.</p></div><div class="mini"><strong>진단에는 어떻게 반영?</strong><p>해당 문항을 0점 처리하지 않고, 기술점수 산정에서 제외하거나 보수적으로 처리하며 진단 신뢰도를 낮춥니다.</p></div><div class="mini"><strong>그 다음에는?</strong><p>CTO·개발·생산담당자 확인 또는 최소 자료를 확보하도록 결과의 Next Best Evidence에 표시합니다.</p></div></div><div class="notice"><b>활용 예:</b> 대표가 “실제환경 검증 여부를 모름”이라고 답했다면 낮은 기술점수를 주는 대신, “기술수준 미확정 → PoC 결과·운영로그 확인 필요”로 처리합니다.</div>${qs.map((q,i)=>`<div class="ev-card"><div class="ev-head"><b>${i+1}. ${q.t}<span class="reason-chip">${evidenceReason(q)}</span></b><span>진단응답: ${answerLabel(q)}</span></div><div class="evidence">${EVIDENCE.map(e=>`<button class="epill ${Number(state.evidence[q.id]??0)===e.k?"selected":""}" onclick="setEv('${q.id}',${e.k})">${e.name}</button>`).join("")}</div><div class="anchor">${ev(q.id).desc}</div></div>`).join("")}<div class="actions"><button class="btn" onclick="navTo(3)">← 이전</button><button class="btn primary" onclick="navTo(5)">통합 진단결과 생성 →</button></div></div>`}
function setEv(id,v){state.evidence[id]=v;evidence()}


function calc(){state.results=evaluate(state)}
const band=engineBand;
function topDimensions(r){const HOLD=["판단 보류",null];let arr=[["기술성숙",r.m.tech],["R&D 역량",r.m.rd],["실행준비",r.m.exec],["기술기록",r.m.evidence],["확장준비",r.m.scale],["전략정렬",r.m.strategy],["리스크대응",r.m.risk]];arr=arr.filter(x=>x[1]!==null);return{strong:arr.length?[...arr].sort((a,b)=>b[1]-a[1]).slice(0,2):[HOLD],weak:arr.length?[...arr].sort((a,b)=>a[1]-b[1]).slice(0,3):[HOLD]}}
function rootCause(area){let d={"기술성숙":"실제환경 검증기준 또는 반복 실증이 충분히 정의되지 않았을 가능성이 있습니다.","R&D 역량":"R&D 자원·실험·산출물·사업성과가 한 관리체계로 연결되지 않았을 가능성이 있습니다.","실행준비":"기술개발이 개인 책임과 경험에 의존하고 완료기준·KPI가 약할 가능성이 있습니다.","기술기록":"기술 자체보다 문서화·버전·시험·변경이력의 추적성이 부족할 가능성이 있습니다.","확장준비":"현재 규모에서는 동작하지만 고객·생산·트래픽 증가 시 병목을 검증하지 않았을 가능성이 있습니다.","전략정렬":"내부 개발과제와 시장·정부 기술로드맵·R&D/IP/인증이 분리되어 있을 가능성이 있습니다.","리스크대응":"외주·API·공급망·핵심인력·규제 의존의 중단 시나리오가 정의되지 않았을 가능성이 있습니다."};return d[area]||"추가 확인이 필요합니다."}
function actionText(area){let d={"기술성숙":["실제환경 검증기준 정의","현장 PoC 성공조건과 실패기준을 먼저 확정합니다.","기술책임자","2~4주","PoC 성공기준 100% 문서화"],"R&D 역량":["R&D 활동-성과 연결표 구축","개발과제·실험·산출물·사업성과를 한 흐름으로 관리합니다.","R&D 책임자","2주","진행 R&D 과제 100% 연결"],"실행준비":["기술과제 책임·완료기준 명확화","누가 언제 무엇을 완료하면 끝인지 기준을 정합니다.","대표/CTO","1주","P0 과제 Owner·Due Date 100% 지정"],"기술기록":["핵심기술 1페이지 정의서 작성","기술명·원리·차별점·현재수준·근거를 한 장으로 정리합니다.","기술담당","1주","핵심기술 정의서 100% 확보"],"확장준비":["Scale-up 병목 테스트","사용량·생산량 증가 시 가장 먼저 깨지는 지점을 검증합니다.","운영/생산","4~8주","병목 Top3와 한계치 확인"],"전략정렬":["공식 로드맵과 개발과제 Crosswalk","로드맵 세부분야와 내부 개발과제를 연결합니다.","대표/R&D","2주","핵심기술 Top3 매핑 완료"],"리스크대응":["외부의존도·대체경로 정의","외주·API·공급자·핵심인력 중단 시 대체경로를 준비합니다.","CTO/운영","2~3주","고위험 의존 Top5 대응책 수립"]};return d[area]||["핵심 문항 응답·담당자 확인","모름으로 남은 문항을 CTO·기술담당자와 함께 확인해 점수 산정 근거를 확보합니다.","대표/CTO","1~2주","핵심 문항 응답률 90% 이상"]}
function nextEvidence(area){let m={"기술성숙":"실제환경 PoC 결과·시험성적·운영로그","R&D 역량":"R&D 계획·실험기록·기술개발 산출물","실행준비":"담당자·일정·완료기준이 있는 기술과제표","기술기록":"핵심기술 정의서·버전이력·시험기록","확장준비":"부하테스트·양산성 검토·병목분석","전략정렬":"공식 기술로드맵 매칭근거·전략품목 Crosswalk","리스크대응":"대체공급자·백업설계·보안/규제 체크리스트"};return m[area]||"담당자 확인 응답·최소 증빙자료"}
function roadmapInput(){return {roadmapField:state.company.roadmapField,texts:[state.company.product,state.company.sectorDetail,state.discovery.hardPart,state.discovery.automated,state.discovery.data,...state.inventory.filter(x=>x.critical).map(x=>x.name)]}}
function roadmapCandidates(){return engineRoadmapCandidates(roadmapInput())}
function otherCandidates(){return otherFieldCandidates(roadmapInput())}
function itemId(m){return m.code?esc(m.code):m.itemNo?`원문 순번 ${esc(m.itemNo)}`:""}
function matchCard(m,i){const techs=(m.matchedTechs||[]).map(t=>`<li>${esc(t.name)}${t.trl?` <span class="subtle">· TRL ${esc(t.trl)}</span>`:""}${t.page?` <span class="subtle">· p.${t.page}</span>`:""}</li>`).join("");return`<div class="match-card"><div><span class="tag blue">후보 ${i+1}</span>${m.weak?' <span class="tag warn">약한 후보</span>':""} <b>${esc(m.name)}</b> <span class="subtle">${itemId(m)}</span><div class="reason">${esc(m.reason)}</div>${techs?`<ul class="match-techs">${techs}</ul>`:""}<div class="src">출처: ${esc(m.source)}</div>${m.uid?`<div data-ev-uid="${esc(m.uid)}">${evidenceHtml(m.uid)}</div>`:""}${m.trlNote?`<div class="src">※ ${esc(m.trlNote)}</div>`:""}<div class="subtle" style="margin-top:6px"><b>활용:</b> 원문 해당 쪽의 개발목표·핵심기술과 자사 기술을 대조해 Crosswalk를 작성합니다.</div></div><div class="match-score"><strong style="font-size:15px">${m.page?`p.${m.page}`:"쪽 미확인"}</strong><span>${m.evidenceGrade==="retrieved"?"원문 색인":"원문"}</span><span>내용 검증 전</span></div></div>`}
/** 핵심기술 이름만으로 선택 분야에서 찾은 품목(없으면 null) — PDF 정렬표에서 기술별로 근거 있는 후보만 연결 */
function techCandidate(t){const c=engineRoadmapCandidates({roadmapField:state.company.roadmapField,texts:[t.name]})[0];return c&&c.hits>0?c:null}
// ---- 원문 근거(Phase 3 Hybrid RAG): VITE_ROADMAP_EVIDENCE=on 일 때만 서버 함수 호출. 실패·미설정이면 표시하지 않는다.
const EVIDENCE_ON=import.meta.env.VITE_ROADMAP_EVIDENCE==="on";
let rmEvidence={key:"",items:{},status:"idle"};
function evidenceQuery(){const x=roadmapInput();return x.texts.filter(Boolean).join(" ").slice(0,600)}
function evidenceHtml(uid){const q=(rmEvidence.items[uid]||[]);return q.length?`<div class="rm-evidence">${q.map(e=>`<div class="ev-quote"><span class="tag ok">원문 근거</span> <span class="subtle">${esc(e.label)}${e.technologyName?` · ${esc(e.technologyName)}`:""}${e.trl?` · TRL ${esc(e.trl)}`:""}</span><blockquote>“${esc(e.quote)}”</blockquote><div class="src">${esc(e.citation)}</div></div>`).join("")}</div>`:""}
function evidenceNote(){return rmEvidence.status==="ok"?`<b>원문 근거</b>는 공식 로드맵 원문에서 그대로 발췌한 문장입니다(요약·생성 없음)${rmEvidence.mode==="keyword_only"?" · 현재 키워드 검색만 사용(의미 검색 꺼짐)":" · 키워드+의미 검색"}. 해당 쪽 원문으로 최종 확인하세요.`:"다음 단계(Hybrid RAG)에서 원문 문장 검색을 연결해 <b>개발목표·핵심기술 정의 원문 인용</b>까지 함께 제시합니다."}
function loadEvidence(matches){if(!EVIDENCE_ON)return;const uids=matches.map(m=>m.uid).filter(Boolean);if(!uids.length)return;const key=evidenceQuery()+"|"+uids.join(",");if(rmEvidence.key===key&&rmEvidence.status!=="error")return;rmEvidence={key,items:{},status:"loading"};fetch("/api/roadmap-evidence",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({query:evidenceQuery(),itemUids:uids})}).then(r=>r.ok?r.json():null).then(j=>{if(rmEvidence.key!==key)return;rmEvidence={key,items:j&&j.status==="ok"?j.items:{},status:j&&j.status==="ok"?"ok":"off",mode:j&&j.mode};document.querySelectorAll("[data-ev-uid]").forEach(el=>{el.innerHTML=evidenceHtml(el.getAttribute("data-ev-uid"))});document.querySelectorAll("[data-ev-note]").forEach(el=>{el.innerHTML=evidenceNote()});buildPrintReport()}).catch(()=>{if(rmEvidence.key===key)rmEvidence.status="error"})}
function otherFieldNote(){const o=otherCandidates();return o.length?`<div class="notice"><b>다른 분야에서 더 많이 일치한 품목:</b> ${o.map(x=>`${esc(x.field)} › <b>${esc(x.name)}</b> (${itemId(x)}${x.page?`, p.${x.page}`:""})`).join(" / ")} — '기술로드맵 기준 분야' 선택을 재검토해 보세요.</div>`:""}
function criticalTechRows(){return state.inventory.filter(x=>x.critical).map(t=>({...t,...nextTrlGate(t.trl)}))}
const riskItems=()=>engineRiskItems(state.answers);
function roadmap(){let r=state.results,o={d90:[],y1:[],y3:[],y5:[]},add=(k,x)=>{if(!o[k].includes(x))o[k].push(x)};r.gaps.forEach(g=>{if(g.area==="기술성숙"){add("d90","핵심기능 성공기준·검증조건 정의");add("y1","외부환경 PoC·반복검증");add("y3","핵심기술 고도화·차세대 기술 확보")}if(g.area==="R&D 역량"){add("d90","R&D 자원·활동·산출·성과 현황표 작성");add("y1","실험·개발·성과측정 체계 정착");add("y3","R&D 포트폴리오·IP·인증 연계")}if(g.area==="실행준비"){add("d90","과제별 담당·일정·완료기준 지정");add("y1","분기 기술 KPI·리뷰 운영")}if(g.area==="기술기록"){add("d90","핵심기술 정의서·시험기록 구축");add("y1","개발이력·검증 근거체계 정착")}if(g.area==="확장준비"){add("d90","확장 병목·외부의존도 목록화");add("y1","Scale-up 테스트·운영표준화");add("y3","양산·대규모 운영체계 구축")}if(g.area==="전략정렬"){add("d90","공식 기술로드맵 Top3와 핵심기술 Crosswalk 작성");add("y1","R&D·IP·인증과 개발계획 연계");add("y3","산업변화 기반 기술포트폴리오 재편")}if(g.area==="리스크대응"){add("d90","외주·API·공급망·핵심인력 리스크 식별");add("y1","대체기술·백업·보안·규제 대응체계 구축")}});add("y5","차세대 기술·글로벌 기준 기술포트폴리오 재설계");add("y5","핵심기술 플랫폼화·데이터 자산화");return o}
function kpi(n,v){if(v===null||v===undefined)return `<div class="score-card"><small>${n}</small><strong>—</strong><span>판단 보류</span></div>`;v=Math.round(v);return `<div class="score-card"><small>${n}</small><strong>${v}<span style="font-size:12px">/100</span></strong><span>${band(v)}</span></div>`}
function radarSVG(m){let data=[["기술",m.tech],["R&D",m.rd],["실행",m.exec],["기록",m.evidence],["확장",m.scale],["전략",m.strategy],["리스크",m.risk]].map(d=>d[1]===null?[d[0]+"(보류)",0]:d),cx=150,cy=145,R=105,n=data.length,pts=r=>data.map((d,i)=>{let a=-Math.PI/2+i*2*Math.PI/n;return`${cx+Math.cos(a)*R*r},${cy+Math.sin(a)*R*r}`}).join(" "),poly=data.map((d,i)=>{let a=-Math.PI/2+i*2*Math.PI/n,r=d[1]/100;return`${cx+Math.cos(a)*R*r},${cy+Math.sin(a)*R*r}`}).join(" ");let axes=data.map((d,i)=>{let a=-Math.PI/2+i*2*Math.PI/n,x=cx+Math.cos(a)*R,y=cy+Math.sin(a)*R,lx=cx+Math.cos(a)*(R+23),ly=cy+Math.sin(a)*(R+23);return`<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="#d0d5dd"/><text x="${lx}" y="${ly}" text-anchor="middle" font-size="10" fill="#475467">${d[0]}</text>`}).join("");return`<svg viewBox="0 0 300 295" width="100%"><polygon points="${pts(.25)}" fill="none" stroke="#e4e7ec"/><polygon points="${pts(.5)}" fill="none" stroke="#e4e7ec"/><polygon points="${pts(.75)}" fill="none" stroke="#e4e7ec"/><polygon points="${pts(1)}" fill="none" stroke="#d0d5dd"/>${axes}<polygon points="${poly}" fill="rgba(79,102,176,.16)" stroke="#4f66b0" stroke-width="2"/></svg>`}
function bars(g){return`<div class="bars">${g.map(x=>`<div class="barrow"><b>${x.area}</b><div class="bartrack"><i style="width:${x.score}%"></i></div><span>${x.score}</span></div>`).join("")}</div>`}
function phase(t,sub,a){return`<div class="phase"><span class="tag">${sub}</span><h3>${t}</h3>${a.length?`<ul>${a.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`:`<p class="hint">추가 과제 도출 필요</p>`}</div>`}
function gapText(a,s){let low=s<45,mid=s<65,map={"기술성숙":low?"실제환경 검증과 성공기준 정의가 우선입니다.":mid?"반복검증과 제품화 기준 보완이 필요합니다.":"기술고도화 단계입니다.","R&D 역량":low?"R&D 자원·활동·성과 연결이 부족합니다.":mid?"R&D 관리·성과측정 표준화가 필요합니다.":"R&D 체계가 비교적 안정적입니다.","실행준비":low?"담당·일정·완료기준이 불명확합니다.":mid?"과제관리 체계 보완이 필요합니다.":"실행체계가 안정적입니다.","기술기록":low?"기술을 설명·검증할 근거가 부족합니다.":mid?"핵심 기록 표준화가 필요합니다.":"대외검증 준비도가 높습니다.","확장준비":low?"성장 시 병목 가능성이 큽니다.":mid?"확장 기준과 검증이 필요합니다.":"확장 준비도가 양호합니다.","전략정렬":low?"시장·정책·산업방향과 기술계획 연결이 부족합니다.":mid?"R&D·IP·인증과 기술계획 연결을 구체화해야 합니다.":"전략 방향과 연계 가능성이 높습니다.","리스크대응":low?"외부의존·인력·규제 대응이 우선입니다.":mid?"대응책 구체화가 필요합니다.":"리스크 관리 준비도가 양호합니다."};return map[a]||"응답 근거가 부족해 점수를 산정하지 않았습니다. 담당자 확인이 우선입니다."}

function dimensionDetail(area,score){
 let low=score<45,mid=score<65;
 const d={
  "기술성숙":{why:"핵심기술이 실제 고객·현장 환경에서 반복적으로 작동하는지 확인하는 영역입니다.",good:"핵심기능 구현과 실증 경험이 기술자산으로 연결되고 있습니다.",weak:"개념·내부 테스트와 실제환경 검증 사이의 간극이 큽니다.",improve:["핵심기능별 성공/실패 기준 정의","실제환경 PoC 설계 및 반복검증","TRL별 다음 Gate와 책임자 지정"],kpi:"핵심기술별 다음 TRL Gate 통과율"},
  "R&D 역량":{why:"기술개발 자원·실험·산출물·사업성과가 체계적으로 연결되는지 봅니다.",good:"R&D 활동이 반복 가능하고 산출물 관리가 비교적 안정적입니다.",weak:"개별 프로젝트는 있으나 자원·실험·성과가 하나의 관리체계로 연결되지 않았습니다.",improve:["R&D 과제-실험-산출물 연결표 구축","분기별 기술 KPI 리뷰","R&D 산출물의 IP·인증·사업화 연계"],kpi:"R&D 과제별 산출물·성과 연결률"},
  "실행준비":{why:"기술과제가 담당자·일정·완료기준을 가지고 실제로 실행되는지 봅니다.",good:"과제 책임과 관리 기준이 비교적 명확합니다.",weak:"기술개발이 개인 경험에 의존하고 완료기준과 우선순위가 모호합니다.",improve:["P0/P1/P2 기술과제 분류","Owner·Due Date·완료기준 100% 지정","주간/월간 기술리뷰 운영"],kpi:"P0 과제 일정 준수율"},
  "기술기록":{why:"기술이 있어도 외부에서 재현·검증할 수 있는 기록이 없으면 기술자산화가 어렵습니다.",good:"개발·시험·변경이력이 비교적 추적 가능합니다.",weak:"기술의 실체보다 기록과 증빙의 추적성이 부족합니다.",improve:["핵심기술 1페이지 정의서 작성","시험·실패·개선 이력 템플릿 통일","버전·변경관리 규칙 수립"],kpi:"핵심기술 Evidence 확보율"},
  "확장준비":{why:"현재 성공이 고객·생산·트래픽 증가 시에도 유지되는지 평가합니다.",good:"확장 시 병목을 인지하고 대응체계를 갖추고 있습니다.",weak:"현재 규모에서는 동작하지만 확장 시 한계와 병목이 충분히 검증되지 않았습니다.",improve:["병목 Top3 식별","부하/양산/운영 시나리오 테스트","품질·비용·납기 한계치 정의"],kpi:"확장 시나리오 검증 완료율"},
  "전략정렬":{why:"내부 개발과제가 시장·산업·정부 기술로드맵과 연결되는지를 봅니다.",good:"핵심기술이 외부 기술방향과 비교적 잘 연결됩니다.",weak:"기술개발과 시장·정책·R&D·IP 계획이 분리되어 있습니다.",improve:["공식 로드맵 Top3 Crosswalk 작성","R&D·IP·인증 일정 통합","연 1회 기술포트폴리오 재검토"],kpi:"핵심기술-로드맵 매핑 완료율"},
  "리스크대응":{why:"외주·API·공급망·핵심인력·규제 중단 시 기술과 사업이 지속 가능한지 봅니다.",good:"주요 기술리스크와 대체경로가 비교적 정의되어 있습니다.",weak:"핵심 의존요소가 중단될 때 대체경로와 복구기준이 부족합니다.",improve:["Dependency Map 작성","고위험 의존 Top5 대체책 수립","보안·인증·규제 사전 점검"],kpi:"고위험 의존요소 대응책 확보율"}
 };
 let x=d[area]||{why:"추가 확인이 필요한 영역입니다.",good:"현재 준비도가 양호합니다.",weak:"보완이 필요합니다.",improve:["추가 분석"],kpi:"추가 KPI 정의"};
 if(score===null||score===undefined)return {...x,interpret:"응답이 없어 판단을 보류했습니다. 담당자 확인 후 재진단하면 해석을 제공합니다."};
 return {...x,interpret:low?x.weak:mid?`${x.weak} 다만 일부 기반은 형성되어 있어 표준화와 반복관리가 우선입니다.`:x.good};
}
function detailedRoadmap(r){
 let top=r.gaps.slice(0,3),names=top.map(g=>g.area),actions=top.map(g=>actionText(g.area));
 return {
  d30:[`진단결과를 CTO·기술담당자와 재확인`,`${names[0]}의 현 상태와 완료기준 문서화`,`핵심기술·TRL·Evidence 목록 확정`],
  d60:[`${actions[0][0]} 착수 및 중간점검`,`${names[1]||names[0]} 개선과제 실행`,`로드맵 매칭 후보와 내부 개발과제 Crosswalk 작성`],
  d90:[`${actions[0][0]} 1차 완료`,`${names[2]||names[0]} 개선결과 Evidence 확보`,`90일 재진단 및 점수·신뢰도 변화 비교`],
  y1:["핵심기술별 TRL 다음 Gate 최소 1단계 진전","분기별 기술 KPI·Evidence 리뷰 정착","R&D·IP·인증·사업화 일정 통합","외부 고객/현장 검증 반복"],
  y3:["핵심기술 포트폴리오 고도화","Scale-up·표준화·품질체계 정착","전략품목·시장 변화에 따른 차세대 기술 확보","외부 공동R&D·전문기관 검증 확대"],
  y5:["차세대 핵심기술·플랫폼/데이터 자산화","글로벌 표준·인증·시장 요구수준 대응","기술 의존도 축소와 독자기술 비중 확대","재진단 데이터를 활용한 기술투자 우선순위 최적화"]
 };
}
function horizonCard(title,sub,items){return `<div class="horizon-card"><h4>${title}</h4><p>${sub}</p><ul>${items.map(x=>`<li>${x}</li>`).join("")}</ul></div>`}
function dimensionCard(name,score){let d=dimensionDetail(name,score);return `<div class="detail-card"><div class="scoreline"><h4>${name}</h4><span class="tag ${score===null?"":score<45?"bad":score<65?"warn":"ok"}">${score===null?"판단 보류":`${Math.round(score)}/100 · ${band(score)}`}</span></div><p><b>해석</b> ${d.interpret}</p><p><b>왜 중요한가</b> ${d.why}</p><ul>${d.improve.map(x=>`<li>${x}</li>`).join("")}</ul><p><b>KPI</b> ${d.kpi}</p></div>`}
function dimensionBars(r){let arr=[["기술성숙",r.m.tech],["R&D 역량",r.m.rd],["실행준비",r.m.exec],["기술기록",r.m.evidence],["확장준비",r.m.scale],["전략정렬",r.m.strategy],["리스크대응",r.m.risk]].sort((a,b)=>(a[1]??101)-(b[1]??101));return `<div class="dimension-list">${arr.map(x=>`<div class="dimension-row"><b>${x[0]}</b><div class="dimension-track"><i style="width:${Math.round(x[1]??0)}%"></i></div><span>${x[1]===null?"보류":Math.round(x[1])}</span></div>`).join("")}</div>`}
function result(){
 calc();
 let r=state.results,dims=topDimensions(r),matches=roadmapCandidates(),crit=criticalTechRows(),risks=riskItems(),rm=roadmap(),dr=detailedRoadmap(r),vm=buildReportViewModel(state,r),{complete,evidenceAvg:evAvg,techConfirmed:confirm,consistencyWarnings:cons,roadmapFieldSet:roadmapOK}=vm.quality;
 let primary=r.gaps[0],primaryAction=actionText(primary.area),dimsAll=[["기술성숙",r.m.tech],["R&D 역량",r.m.rd],["실행준비",r.m.exec],["기술기록",r.m.evidence],["확장준비",r.m.scale],["전략정렬",r.m.strategy],["리스크대응",r.m.risk]];
 $("s5").innerHTML=`<div class="report-nav no-print"><a href="#summary">경영진 요약</a><a href="#deep">상세진단</a><a href="#tech">핵심기술</a><a href="#roadmapfit">로드맵 정렬</a><a href="#action">실행계획</a><a href="#horizon">중장기 로드맵</a><a href="#risk">리스크</a><a href="#qa">품질점검</a></div>
 <div id="summary" class="panel report-section"><div class="module-summary"><span class="tag ${r.level==="잠정진단"?"warn":"ok"}">${r.level}</span><span class="tag">${state.company.roadmapField}</span><span class="tag">응답 ${r.answered}/${activeQs().length}</span></div><h2>6. 통합 기술진단 결과</h2><p class="desc">점수보다 “현재 어디에 있고, 왜 그런지, 무엇을 먼저 해야 하는지”를 경영 의사결정 관점에서 해석합니다.</p>${r.insufficient?`<div class="alert red"><b>진단 미완료:</b> 핵심 응답이 ${r.answered}개입니다. 결과는 잠정 참고용입니다.</div>`:""}<div class="decision"><h3>경영진 결론</h3><p>현재 기술역량은 <strong>${capText(r.capability)}</strong> 수준으로 추정됩니다. 가장 큰 병목은 <strong>${primary.area}</strong>이며, 우선 실행과제는 <strong>${primaryAction[0]}</strong>입니다. 진단신뢰도는 <strong>${Math.round(r.confidence)}/100</strong>으로 ${r.confidence<60?"기술수준 자체보다 판단근거의 불확실성이 큰 상태입니다. CTO·개발·생산담당자 확인과 Evidence 확보를 선행해야 합니다.":"실행계획 수립이 가능한 수준이지만, 핵심기술별 KPI와 Evidence를 동시에 관리해야 합니다."}</p></div><div class="score-grid" style="margin-top:13px">${kpi("기술역량",r.capability)}${kpi("진단 신뢰도",r.confidence)}${kpi("가장 강한 영역",dims.strong[0][1])}${kpi("가장 약한 영역",dims.weak[0][1])}</div><div class="result-use" style="margin-top:13px"><div class="mini"><h4>경영회의</h4><p>P0 기술과제·예산·담당자 결정에 활용합니다.</p></div><div class="mini"><h4>R&D·지원사업</h4><p>기술 Gap, TRL, Evidence 보완사항을 사업계획에 연결합니다.</p></div><div class="mini"><h4>재진단</h4><p>90일 후 동일 기준으로 다시 측정해 실행효과를 비교합니다.</p></div></div></div>
 <div id="deep" class="panel report-section"><h2>7개 영역 상세진단</h2><p class="desc">유사한 그래프를 반복하지 않고, 하나의 비교차트와 영역별 질적 해석으로 구성했습니다.</p><div class="viz"><h3>현재 역량 비교</h3><p>낮은 영역부터 병목과 개선과제를 확인합니다.</p>${dimensionBars(r)}</div><div class="detail-grid" style="margin-top:13px">${dimsAll.map(x=>dimensionCard(x[0],x[1])).join("")}</div></div>
 <div id="tech" class="panel report-section"><h2>핵심기술별 성숙도·다음 Gate</h2><p class="desc">기업 전체 점수가 아니라 핵심기술별 다음 검증 Gate를 제시합니다.</p><div class="tablewrap"><table><thead><tr><th>핵심기술</th><th>보유형태</th><th>현재 TRL</th><th>다음 목표</th><th>다음 Gate</th><th>권고 Evidence</th><th>상태</th></tr></thead><tbody>${crit.map(t=>`<tr><td><b>${esc(t.name)}</b></td><td>${esc(t.ownership)}</td><td>${t.trl?`TRL ${t.trl}`:"확인 필요"}</td><td>${t.target}</td><td>${t.gate}</td><td>${t.trl&&t.trl>=7?"실사용 성능·운영로그·고객 검증":"시험기록·PoC·성능지표·개선이력"}</td><td>${t.confirmed?"기업확인":"추가확인"}</td></tr>`).join("")||`<tr><td colspan="7">핵심기술을 먼저 지정해 주세요.</td></tr>`}</tbody></table></div></div>
 <div id="roadmapfit" class="panel report-section"><h2>기술로드맵 정렬 · 참고 후보</h2><p class="desc">선택한 <b>${esc(state.company.roadmapField)}</b> 분야의 공식 로드맵 원문 색인(전략품목·핵심기술명·원문 쪽)에서 입력 내용과 단어가 겹치는 <b>전략품목</b>을 찾았습니다. 키워드 일치 순서이며 적합도 판정이 아니므로, 원문 해당 쪽을 확인해 최종 판단하세요.</p><div class="roadmap-match">${matches.map(matchCard).join("")}</div>${otherFieldNote()}${(loadEvidence(matches),"")}<div class="notice" data-ev-note>${evidenceNote()}</div></div>
 <div id="action" class="panel report-section"><h2>90일 실행계획</h2><p class="desc">실행과제는 담당·기간·KPI·Evidence까지 연결해 실제 회의와 프로젝트 관리에 사용할 수 있도록 구성합니다.</p><div class="tablewrap"><table><thead><tr><th>우선</th><th>영역</th><th>실행과제</th><th>담당</th><th>기간</th><th>KPI/완료기준</th><th>다음 Evidence</th></tr></thead><tbody>${r.gaps.map(g=>{let a=actionText(g.area);return`<tr><td><span class="tag ${g.priority==="P0"?"bad":g.priority==="P1"?"warn":"ok"}">${g.priority}</span></td><td>${g.area}</td><td><b>${a[0]}</b><br><span class="subtle">${a[1]}</span></td><td>${a[2]}</td><td>${a[3]}</td><td>${a[4]}</td><td>${nextEvidence(g.area)}</td></tr>`}).join("")}</tbody></table></div><h3 style="margin-top:18px">30·60·90일 Milestone</h3><div class="roadmap-depth">${horizonCard("30일","진단 확정·기준정의",dr.d30)}${horizonCard("60일","우선과제 실행·중간검증",dr.d60)}${horizonCard("90일","성과확인·재진단",dr.d90)}${horizonCard("재진단","동일 기준으로 변화 확인",["기술역량·신뢰도 변화 비교","P0 과제 완료율 확인","다음 분기 P0/P1 재설정"])}</div></div>
 <div id="horizon" class="panel report-section"><h2>1년 · 3년 · 5년 기술성장 로드맵</h2><p class="desc">장기 로드맵은 ‘기술개발 목록’이 아니라 목표상태·운영체계·검증기준을 함께 제시합니다.</p><div class="roadmap-depth">${horizonCard("1년","검증·제품화·운영체계 정착",dr.y1)}${horizonCard("3년","고도화·Scale-up·기술포트폴리오",dr.y3)}${horizonCard("5년","차세대·글로벌·기술자산화",dr.y5)}${horizonCard("공통 KPI","기간별 공통 측정기준",["핵심기술 TRL Gate 통과율","P0/P1 과제 완료율","Evidence 확보율","외부 고객/기관 검증 건수","기술 의존도·리스크 감소율"])}</div><div class="notice"><b>로드맵 운영원칙:</b> 3·5년 계획은 고정계획이 아니라 매년 공식 로드맵·시장·기술변화를 반영해 재설계해야 합니다.</div></div>
 <div id="risk" class="panel report-section"><h2>리스크 레드팀</h2><p class="desc">진단 결과가 틀릴 수 있는 지점과 기술성장 계획을 방해할 요인을 함께 표시합니다.</p><div class="risk-grid">${risks.length?risks.map(x=>`<div class="risk-card"><h4>${x[0]}</h4><p>${x[2]}</p><div class="riskline"><span class="tag ${x[1].includes("높음")?"bad":"warn"}">${x[1]}</span></div></div>`).join(""):`<div class="risk-card"><h4>주요 고위험 신호 없음</h4><p>현재 자가응답 기준입니다. 외부 검증 전에는 잠재리스크가 남아 있습니다.</p></div>`}</div><div class="alert" style="margin-top:12px"><b>과대해석 금지:</b> 로드맵 포함 여부는 기술우수성·시장성·정부지원 선정 가능성을 의미하지 않습니다. TRL도 기술 자체의 성숙도이며 기업가치나 사업성 등급이 아닙니다.</div></div>
 <div id="qa" class="panel report-section"><h2>진단 품질 모니터링 · Red Team QA</h2><div class="qa-grid"><div class="qa-card"><small>응답완료</small><b><span class="dotstatus ${complete>=90?"ok":complete>=70?"warn":"bad"}"></span>${complete}%</b></div><div class="qa-card"><small>근거강도</small><b><span class="dotstatus ${evAvg>=75?"ok":evAvg>=55?"warn":"bad"}"></span>${evAvg}%</b></div><div class="qa-card"><small>기술확인</small><b><span class="dotstatus ${confirm>=75?"ok":confirm>=50?"warn":"bad"}"></span>${confirm}%</b></div><div class="qa-card"><small>일관성 경고</small><b><span class="dotstatus ${cons===0?"ok":cons<=2?"warn":"bad"}"></span>${cons}건</b></div><div class="qa-card"><small>로드맵 출처</small><b><span class="dotstatus ${roadmapOK?"ok":"warn"}"></span>${roadmapOK?"분야 지정":"미지정"}</b></div></div><details><summary>검증 전제와 한계 보기</summary><div class="subtle" style="margin-top:8px">현재 문항·가중치·우선순위 공식은 POC입니다. 정식 서비스 전 전문가 내용타당도(CVI/CVR), 대표자 Cognitive Interview, 기업 Pilot, 문항분석·신뢰도, 외부평가와 수렴타당도, 업종·규모별 Calibration이 필요합니다. 로드맵 매칭도 Gold Set을 만들어 Hit@K·NDCG·Citation Accuracy·Groundedness를 별도로 검증해야 합니다.</div></details><div class="actions no-print"><button class="btn" onclick="navTo(4)">← 근거 확인</button><div><button class="btn" onclick="saveState()">결과 저장</button> <button class="btn primary" onclick="printReport()">PDF 인쇄</button></div></div></div>`
}

function reportId(){return vmReportId(state.company.name)}
function reportDate(){return new Date().toLocaleDateString('ko-KR',{year:'numeric',month:'2-digit',day:'2-digit'})}
function prFooter(n,total=13){return `<div class="pr-footer"><span>BECONIC · ${ISSUER.shortName} · 중기부 인증 ${ISSUER.certificationShort.replace(/^.*(제\S+호)$/,"$1")} · Confidential</span><span>${reportId()} · ${n} / ${total}</span></div>`}
function prHead(section,n,total=13){return `<div class="pr-head"><b>BECONIC TECHNOLOGY GROWTH REPORT</b><span>${esc(state.company.name||'진단기업')} · ${section}</span></div>`}
function prPage(n,section,body,total=13){return `<section class="pr-page">${prHead(section,n,total)}${body}${prFooter(n,total)}</section>`}
function prMetric(name,value,note=''){return `<div class="pr-metric"><small>${name}</small><strong>${value===null||value===undefined?"—":Math.round(value)}</strong><span>${note||band(value??null)}</span></div>`}
function prBars(r){
  const arr=[["기술성숙",r.m.tech],["R&D 역량",r.m.rd],["실행준비",r.m.exec],["기술기록",r.m.evidence],["확장준비",r.m.scale],["전략정렬",r.m.strategy],["리스크대응",r.m.risk]];
  return `<div class="pr-barlist">${arr.map(x=>`<div class="pr-barrow"><b>${x[0]}</b><div class="pr-bar"><i style="width:${Math.round(x[1]??0)}%"></i></div><span>${x[1]===null?"보류":Math.round(x[1])}</span></div>`).join('')}</div>`;
}
const strategicOptions=r=>engineStrategicOptions(r);
function quarterPlan(r){
  const top=r.gaps.slice(0,3).map(g=>g.area),a0=actionText(top[0]),a1=actionText(top[1]||top[0]),a2=actionText(top[2]||top[0]);
  return [
    ['Q1 · 기준 확정',[`${a0[0]} 완료`,`핵심기술·TRL·Evidence 베이스라인 확정`,`P0 과제 Owner·KPI 지정`]],
    ['Q2 · 외부 검증',[`${a1[0]} 실행`,`고객/현장 검증 1차 완료`,`실패·개선 이력 표준화`]],
    ['Q3 · 확장 준비',[`${a2[0]} 실행`,`Scale-up/운영 병목 검증`,`R&D·IP·인증 Crosswalk 보완`]],
    ['Q4 · 재평가·포트폴리오',[`연간 재진단 및 Delta 분석`,`차년도 P0/P1 재설정`,`기술포트폴리오·예산 갱신`]]
  ];
}
function buildPrintReport(){
  if(!$('printReport')) return;
  calc();
  let r=state.results,dims=topDimensions(r),matches=roadmapCandidates(),crit=criticalTechRows(),risks=riskItems(),dr=detailedRoadmap(r),opts=strategicOptions(r),qplan=quarterPlan(r),vm=buildReportViewModel(state,r),{complete,evidenceAvg:evAvg,techConfirmed:confirm}=vm.quality,primary=r.gaps[0],pact=actionText(primary.area);
  const areas=[["기술성숙",r.m.tech],["R&D 역량",r.m.rd],["실행준비",r.m.exec],["기술기록",r.m.evidence],["확장준비",r.m.scale],["전략정렬",r.m.strategy],["리스크대응",r.m.risk]];
  const total=13;
  let html='';
  html+=`<section class="pr-page pr-cover"><div><img class="cover-logo" src="/assets/gv-logo-en-white.svg" alt="Growth Ventures"><div class="eyebrow">Technology Growth Diagnostic Report</div><h1>기업 기술성장<br>진단·실행 로드맵</h1><h2>BECONIC Technology Growth Navigator</h2><div class="cover-company">${esc(state.company.name||'진단기업')}</div><div class="cover-grid"><div><small>기업단계</small><b>${esc(state.company.stage)}</b></div><div><small>기술로드맵 분야</small><b>${esc(state.company.roadmapField)}</b></div><div><small>기업 운영유형</small><b>${esc(state.company.bizType)}</b></div><div><small>진단유형</small><b>${state.mode==='deep'?'정밀진단':'간편진단'}</b></div><div><small>보고서 ID</small><b>${reportId()}</b></div><div><small>작성일</small><b>${reportDate()}</b></div></div></div><div class="conf"><div class="cover-issuer" style="margin:0 0 2mm"><b>발행: ${ISSUER.company}</b> · ${ISSUER.certification} · ${ISSUER.address} · ${ISSUER.phone} · ${ISSUER.email} · ${ISSUER.web}</div>CONFIDENTIAL · 본 보고서는 경영·기술 의사결정 지원용이며 법정 인증, 기술가치평가 또는 투자등급을 대체하지 않습니다.</div></section>`;

  html+=prPage(2,'Executive Summary',`<div class="pr-kicker">Executive Summary</div><h2 class="pr-title">경영진 의사결정 요약</h2><p class="pr-subtitle">점수보다 병목, 신뢰도, 우선 행동과 기대효과를 중심으로 해석합니다.</p><div class="pr-decision"><p>현재 기술역량은 <b>${capText(r.capability)}</b> 수준으로 추정됩니다. 가장 큰 병목은 <b>${primary.area}</b>이며, 90일 최우선 과제는 <b>${pact[0]}</b>입니다. 진단 신뢰도는 <b>${Math.round(r.confidence)}/100</b>으로 ${r.confidence<60?'현재 기술수준보다 먼저 핵심 Evidence와 담당자 확인을 보강해야 합니다.':'현재 결과를 실행계획 기준선으로 활용할 수 있으나 핵심기술별 KPI·Evidence를 병행 관리해야 합니다.'}</p></div><div class="pr-grid4">${prMetric('기술역량',r.capability)}${prMetric('진단 신뢰도',r.confidence,r.level)}${prMetric('최강 영역',dims.strong[0][1],dims.strong[0][0])}${prMetric('최약 영역',dims.weak[0][1],dims.weak[0][0])}</div><div class="pr-divider"></div><div class="pr-grid2"><div class="pr-card soft"><h4>핵심 강점</h4><ul>${dims.strong[0][1]===null?"<li>응답이 부족해 영역별 점수를 산정하지 않았습니다. 핵심 문항 응답과 담당자 확인 후 재진단하면 강점·병목을 제시합니다.</li>":dims.strong.map(x=>`<li><b>${x[0]}</b> ${fmtScore(x[1])} - ${dimensionDetail(x[0],x[1]).interpret}</li>`).join('')}</ul></div><div class="pr-card warn"><h4>우선 개선</h4><ul>${r.gaps.slice(0,3).map(g=>`<li><b>${g.area}</b> ${fmtScore(g.score)} - ${gapText(g.area,g.score)}</li>`).join('')}</ul></div></div><div class="pr-callout"><b>경영진 권고:</b> P0 과제를 별도 프로젝트로 지정하고 Owner·Due Date·KPI·Evidence를 100% 연결한 뒤 90일 후 동일 기준으로 재진단하십시오.</div>`,total);

  html+=prPage(3,'Methodology & Data Quality',`<div class="pr-kicker">Methodology & Evidence</div><h2 class="pr-h2">진단 방법론·데이터 품질</h2><p class="pr-lead">기술수준과 근거수준을 분리하고, 핵심기술 단위 TRL·7개 역량영역·Evidence Confidence를 결합합니다.</p><div class="pr-flow"><div><b>1. Technology Discovery</b><p>사업언어에서 제품·데이터·알고리즘·공정·의존요소를 추출</p></div><div><b>2. Critical Technology</b><p>제품성과를 좌우하는 핵심기술을 선별하고 TRL 확인</p></div><div><b>3. Evidence-aware Assessment</b><p>12개 Core + 산업심화문항, 모름은 0점이 아닌 불확실성</p></div><div><b>4. Action Roadmap</b><p>Gap → 우선순위 → KPI → Evidence → 재진단</p></div></div><div class="pr-divider"></div><div class="pr-grid4">${prMetric('응답완료',complete,'문항 완료율')}${prMetric('근거강도',evAvg,'Evidence 평균')}${prMetric('기술확인',confirm,'기업 확인율')}${prMetric('미확인',r.unknown,`${activeQs().length}개 중`)}</div><div class="pr-grid2" style="margin-top:3mm"><div class="pr-card"><h4>평가원칙</h4><ul><li>기업규모·직원수·업력은 직접 가점하지 않음</li><li>TRL은 기술성숙도이며 기업가치·시장성 점수가 아님</li><li>자가진술과 외부검증을 별도 Confidence로 관리</li><li>로드맵 포함 여부는 기술우수성·선정가능성을 의미하지 않음</li></ul></div><div class="pr-card warn"><h4>현재 검증상태</h4><p>문항·가중치·우선순위는 POC 단계입니다. 정식 서비스 전 전문가 내용타당도(CVI/CVR), Cognitive Interview, 기업 Pilot, 신뢰도·수렴타당도, 업종별 Calibration이 필요합니다.</p></div></div>`,total);

  html+=prPage(4,'Scorecard',`<div class="pr-kicker">Capability Scorecard</div><h2 class="pr-h2">7개 영역 종합 Scorecard</h2><div class="pr-grid2"><div class="pr-card">${prBars(r)}</div><div class="pr-card soft"><h4>Scorecard 해석</h4><p>${dims.weak[0][1]===null?"응답이 부족해 영역별 점수를 산정하지 않았습니다. 핵심 문항 응답과 담당자 확인 후 재진단하면 강점·병목을 제시합니다.":`가장 낮은 영역은 <b>${dims.weak[0][0]}</b> ${fmtScore(dims.weak[0][1])}이며, 가장 높은 영역은 <b>${dims.strong[0][0]}</b> ${fmtScore(dims.strong[0][1])}입니다. 병목영역을 우선 개선하지 않으면 강점영역의 투자효과도 제한될 수 있습니다.`}</p><div class="pr-callout"><b>우선순위 원칙:</b> Gap 크기 + 리스크 + 낮은 Confidence + 전략정렬 필요성을 함께 고려합니다.</div></div></div><div class="pr-divider"></div><table class="pr-table"><thead><tr><th style="width:19%">영역</th><th style="width:11%">점수</th><th style="width:17%">상태</th><th>핵심 해석</th></tr></thead><tbody>${areas.map(x=>`<tr><td><b>${x[0]}</b></td><td>${fmtScore(x[1])}</td><td>${band(x[1])}</td><td>${dimensionDetail(x[0],x[1]).interpret}</td></tr>`).join('')}</tbody></table>`,total);

  const weakDetails=dims.weak.map(x=>({name:x[0],score:x[1],d:dimensionDetail(x[0],x[1])}));
  html+=prPage(5,'Deep Diagnosis',`<div class="pr-kicker">Deep Diagnosis</div><h2 class="pr-h2">핵심 병목·근본원인 가설</h2><p class="pr-lead">아래 원인은 확정판정이 아니라 응답패턴에 근거한 검증가설입니다. 인터뷰·문서·현장데이터로 확인해야 합니다.</p><div class="pr-grid3">${weakDetails.map(x=>`<div class="pr-card ${x.score<45?'bad':'warn'}"><h4>${x.name} · ${Math.round(x.score)}/100</h4><p><b>해석</b> ${x.d.interpret}</p><ul>${x.d.improve.map(z=>`<li>${z}</li>`).join('')}</ul><p style="margin-top:2mm"><b>KPI</b> ${x.d.kpi}</p></div>`).join('')}</div><div class="pr-divider"></div><div class="pr-grid2"><div class="pr-card"><h4>가능한 구조적 원인</h4><ul><li>기술개발과 사업 KPI가 분리되어 개발완료 기준이 모호할 가능성</li><li>핵심인력·외부 API·공급사에 지식과 운영이 집중될 가능성</li><li>실증·시험·실패이력이 기술자산으로 축적되지 않을 가능성</li><li>로드맵·R&D·IP·인증이 개별 일정으로 관리될 가능성</li></ul></div><div class="pr-card soft"><h4>추가 확인 질문</h4><ul><li>현재 P0 기술과제의 Owner와 완료기준이 문서화되어 있는가?</li><li>핵심기술별 최신 시험결과와 실패원인을 다시 찾을 수 있는가?</li><li>외부 고객환경에서 동일 성능을 반복 재현했는가?</li><li>외부 의존요소가 중단될 때 대체경로가 실제 테스트되었는가?</li></ul></div></div>`,total);

  html+=prPage(6,'Critical Technology & TRL',`<div class="pr-kicker">Critical Technology</div><h2 class="pr-h2">핵심기술별 TRL·다음 Gate</h2><p class="pr-lead">기업 전체에 TRL 하나를 부여하지 않고, 핵심기술별 현재 상태와 다음 검증 Gate를 관리합니다.</p><table class="pr-table"><thead><tr><th style="width:23%">핵심기술</th><th style="width:12%">보유형태</th><th style="width:11%">현재</th><th style="width:12%">다음목표</th><th style="width:20%">다음 Gate</th><th>권고 Evidence</th></tr></thead><tbody>${crit.slice(0,6).map(t=>`<tr><td><b>${esc(t.name)}</b></td><td>${esc(t.ownership)}</td><td>${t.trl?`TRL ${t.trl}`:'확인 필요'}</td><td>${t.target}</td><td>${t.gate}</td><td>${t.trl&&t.trl>=7?'실사용 성능·운영로그·고객 검증':'시험기록·PoC·성능지표·개선이력'}</td></tr>`).join('')||`<tr><td colspan="6">핵심기술을 먼저 지정해야 합니다.</td></tr>`}</tbody></table>${crit.length>6?`<div class="pr-source">※ 핵심기술 ${crit.length}건 중 6건만 표시했습니다. 전체 목록은 웹 결과 화면의 '핵심기술별 성숙도·다음 Gate'에서 확인하세요.</div>`:''}<div class="pr-divider"></div><div class="pr-grid2"><div class="pr-card soft"><h4>Technology Fingerprint</h4><p><b>제품/서비스</b> ${esc(state.company.product||'미입력')}</p><p style="margin-top:1.5mm"><b>핵심 차별요소</b> ${esc(state.discovery.hardPart||'미입력')}</p><p style="margin-top:1.5mm"><b>데이터</b> ${esc(state.discovery.data||'미입력')}</p></div><div class="pr-card"><h4>TRL 운영원칙</h4><ul><li>TRL 상승은 다음 Gate를 통과한 근거가 있을 때만 인정</li><li>기술성숙도와 R&D 역량·사업성·시장성은 별도 관리</li><li>TRL 7 이상은 실제환경/운영 Evidence를 우선 요구</li></ul></div></div>`,total);

  html+=prPage(7,'Strategic Alignment',`<div class="pr-kicker">Strategic Alignment</div><h2 class="pr-h2">기술로드맵 정렬(참고 후보)·정책 연계</h2><p class="pr-lead">공식 로드맵 원문 색인에서 입력 내용과 단어가 겹치는 전략품목입니다. 키워드 일치 순서이며 적합도 판정이 아니므로 원문 해당 쪽 확인이 필요합니다.</p><div class="pr-grid3">${matches.map((m,i)=>`<div class="pr-card ${i===0?'soft':''}"><span class="pr-pill">후보 ${i+1}${m.weak?' · 약한 후보':''}</span><h4 style="margin-top:1.5mm">${esc(m.name)}</h4><p>${itemId(m)}${m.page?` · 원문 p.${m.page}`:''}</p>${(m.matchedTechs||[]).length?`<ul>${m.matchedTechs.map(t=>`<li>${esc(t.name)}${t.trl?` (TRL ${esc(t.trl)})`:''}</li>`).join('')}</ul>`:''}${(rmEvidence.items[m.uid]||[]).slice(0,1).map(e=>`<p class="pr-quote">“${esc(e.quote.length>90?e.quote.slice(0,90)+'…':e.quote)}” <span class="pr-source">원문 p.${e.printedPage??'?'}</span></p>`).join('')}<div class="pr-source">${esc(m.source)} · ${m.label}</div></div>`).join('')}</div><div class="pr-divider"></div><table class="pr-table"><thead><tr><th>기업 핵심기술</th><th>로드맵 후보</th><th>연계 활용</th><th>추가 검증</th></tr></thead><tbody>${crit.slice(0,4).map((t,i)=>`<tr><td><b>${esc(t.name)}</b></td><td>${(c=>c?`${esc(c.name)}<br><span class="pr-source">${itemId(c)}${c.page?` · p.${c.page}`:''}</span>`:'이름 일치 품목 없음 — 원문 검토 필요')(techCandidate(t))}</td><td>내부 개발과제·R&D·IP·인증 일정 Crosswalk</td><td>원문 전략품목·핵심기술·개발목표·페이지 확인</td></tr>`).join('')}</tbody></table>${crit.length>4?`<div class="pr-source">※ 핵심기술 ${crit.length}건 중 4건만 표시했습니다.</div>`:''}<div class="pr-callout"><b>RAG 전환 우선순위:</b> Keyword/BM25 + Vector Search + Metadata Filter + Reranking → Top-N 원문 Evidence → Claude 해석 순으로 구성하십시오.</div>`,total);

  html+=prPage(8,'Gap & Root Cause',`<div class="pr-kicker">Gap Intelligence</div><h2 class="pr-h2">기술 Gap·원인·개선방향</h2><table class="pr-table"><thead><tr><th style="width:15%">우선</th><th style="width:18%">영역</th><th style="width:11%">현재</th><th style="width:25%">Gap 해석</th><th>개선방향</th></tr></thead><tbody>${r.gaps.map(g=>{let d=dimensionDetail(g.area,g.score);return`<tr><td><span class="pr-pill ${g.priority==='P0'?'bad':g.priority==='P1'?'warn':'ok'}">${g.priority}</span></td><td><b>${g.area}</b></td><td>${fmtScore(g.score)}</td><td>${gapText(g.area,g.score)}</td><td>${d.improve.slice(0,2).join(' / ')}</td></tr>`}).join('')}</tbody></table><div class="pr-divider"></div><div class="pr-grid2"><div class="pr-card"><h4>원인 → 결과 연결</h4><ul>${r.gaps.slice(0,3).map(g=>{let d=dimensionDetail(g.area,g.score);return`<li><b>${g.area}</b>: ${d.interpret} → ${actionText(g.area)[0]}가 90일 우선과제</li>`}).join('')}</ul></div><div class="pr-card warn"><h4>의사결정 리스크</h4><ul>${(risks.length?risks:[['과대해석 리스크','중간','자가응답만으로 기술우수성·시장성을 확정해서는 안 됩니다.']]).slice(0,4).map(x=>`<li><b>${x[0]}</b> (${x[1]}) - ${x[2]}</li>`).join('')}</ul></div></div>`,total);

  html+=prPage(9,'Strategic Options',`<div class="pr-kicker">Strategic Options</div><h2 class="pr-h2">전략 대안 비교</h2><p class="pr-lead">현재 상태에서 가능한 3개 경로를 비교하고, 실행 전제와 Trade-off를 함께 제시합니다.</p><div class="pr-grid3">${opts.map(o=>`<div class="pr-card pr-option ${o.recommended?'recommended':''}"><div class="opt-head"><b>${o.name}</b><span class="opt-score">${o.recommended?'우선 검토':'대안'}</span></div><p><b>적합 상황</b> ${o.when}</p><p style="margin-top:1.5mm"><b>핵심 Focus</b> ${o.focus}</p><p style="margin-top:1.5mm"><b>Trade-off</b> ${o.trade}</p></div>`).join('')}</div><div class="pr-callout"><b>우선 검토안:</b> ${opts.find(o=>o.recommended).name}. 이는 현재 진단점수와 Evidence 수준을 기반으로 한 POC 의사결정 가이드이며, 실제 투자·예산 결정 전 비용·인력·고객일정을 추가 검증해야 합니다.</div><div class="pr-grid2"><div class="pr-card"><h4>대안 선택 기준</h4><ul><li>기술성숙도와 Evidence Confidence의 균형</li><li>90일 내 검증 가능한가?</li><li>핵심고객·시장진입과 직접 연결되는가?</li><li>외부의존·규제·인력 리스크를 감당할 수 있는가?</li></ul></div><div class="pr-card"><h4>추가 의사결정 데이터</h4><ul><li>과제별 예상비용·필요인력</li><li>고객/현장 확보 가능성</li><li>인증·규제 Lead Time</li><li>IP·경쟁기술·대체기술 조사</li></ul></div></div>`,total);

  html+=prPage(10,'90-Day Execution Plan',`<div class="pr-kicker">90-Day Plan</div><h2 class="pr-h2">90일 실행계획·책임·KPI</h2><table class="pr-table compact"><thead><tr><th style="width:8%">우선</th><th style="width:13%">영역</th><th style="width:25%">실행과제</th><th style="width:12%">담당</th><th style="width:10%">기간</th><th style="width:18%">KPI/완료기준</th><th>Evidence</th></tr></thead><tbody>${r.gaps.map(g=>{let a=actionText(g.area);return`<tr><td><span class="pr-pill ${g.priority==='P0'?'bad':g.priority==='P1'?'warn':'ok'}">${g.priority}</span></td><td>${g.area}</td><td><b>${a[0]}</b><br>${a[1]}</td><td>${a[2]}</td><td>${a[3]}</td><td>${a[4]}</td><td>${nextEvidence(g.area)}</td></tr>`}).join('')}</tbody></table><div class="pr-divider"></div><div class="pr-grid3"><div class="pr-card soft"><h4>0-30일 · 기준확정</h4><ul>${dr.d30.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="pr-card"><h4>31-60일 · 실행·중간검증</h4><ul>${dr.d60.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="pr-card"><h4>61-90일 · 성과확인·재진단</h4><ul>${dr.d90.map(x=>`<li>${x}</li>`).join('')}</ul></div></div><div class="pr-callout"><b>회의 운영:</b> 주간 P0 진행상태, 월간 Evidence·KPI, 90일 종합 재진단의 3단계 Governance를 권장합니다.</div>`,total);

  html+=prPage(11,'12-Month & 3-5 Year Roadmap',`<div class="pr-kicker">Technology Growth Roadmap</div><h2 class="pr-h2">1년·3년·5년 기술성장 로드맵</h2><div class="pr-quarter">${qplan.map(q=>`<div class="pr-card"><h4>${q[0]}</h4><ul>${q[1].map(x=>`<li>${x}</li>`).join('')}</ul></div>`).join('')}</div><div class="pr-divider"></div><div class="pr-road"><div class="pr-card soft"><h4>1년 · 제품화·운영체계</h4><ul>${dr.y1.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="pr-card"><h4>3년 · Scale-up·포트폴리오</h4><ul>${dr.y3.map(x=>`<li>${x}</li>`).join('')}</ul></div><div class="pr-card"><h4>5년 · 차세대·글로벌</h4><ul>${dr.y5.map(x=>`<li>${x}</li>`).join('')}</ul></div></div><div class="pr-callout"><b>로드맵 원칙:</b> 3·5년 계획은 고정계획이 아니라 연 1회 공식 기술로드맵·시장·규제·경쟁환경을 반영해 재설계해야 합니다.</div>`,total);

  const kpis=[['핵심기술 TRL Gate 통과율','분기','기술책임자'],['P0/P1 과제 완료율','월','PM/CTO'],['Evidence 확보율','월','기술담당'],['외부 고객/기관 검증 건수','분기','사업/R&D'],['고위험 의존요소 대응률','분기','운영/CTO'],['기술로드맵 매핑 갱신율','반기','R&D/전략']];
  html+=prPage(12,'Risk, KPI & Governance',`<div class="pr-kicker">Risk & Governance</div><h2 class="pr-h2">리스크·KPI·운영 Governance</h2><div class="pr-risk">${(risks.length?risks:[['과대해석 리스크','중간','자가응답만으로 기술우수성·시장성을 확정하지 않습니다.']]).slice(0,4).map(x=>`<div class="pr-card ${x[1].includes('높음')?'bad':'warn'}"><h4>${x[0]} · ${x[1]}</h4><p>${x[2]}</p></div>`).join('')}</div><div class="pr-divider"></div><table class="pr-table"><thead><tr><th>KPI</th><th style="width:16%">주기</th><th style="width:20%">책임</th><th>의사결정 용도</th></tr></thead><tbody>${kpis.map(k=>`<tr><td><b>${k[0]}</b></td><td>${k[1]}</td><td>${k[2]}</td><td>기술투자 우선순위·로드맵 Gate·재진단 근거</td></tr>`).join('')}</tbody></table><div class="pr-grid3" style="margin-top:3mm"><div class="pr-card"><h4>주간</h4><p>P0 과제 진행·Blocker·Owner 확인</p></div><div class="pr-card"><h4>월간</h4><p>KPI·Evidence·외부의존 리스크 리뷰</p></div><div class="pr-card"><h4>분기/90일</h4><p>재진단·투자우선순위·로드맵 갱신</p></div></div>`,total);

  html+=prPage(13,'Appendix & Limitations',`<div class="pr-kicker">Appendix</div><h2 class="pr-h2">출처·검증상태·한계·다음 고도화</h2><div class="pr-grid2"><div class="pr-card"><h4>현재 Knowledge Base</h4><ul><li>2026~2028 13대 전략분야 로드맵 (색인 연결)</li><li>스마트제조·화장품 특화(2026~2028)·원전 특화(2023~2027) (색인 연결)</li><li>소재·부품·장비 전략품목 정의서 2026.03 (색인 연결)</li><li>2025~2027 로드맵 35개 분야 (이전 판 대조용)</li></ul><p class="pr-source">로드맵 후보는 원문 색인(전략품목·핵심기술명·원문 쪽) 키워드 일치 결과입니다. 원문 문장 인용은 Hybrid RAG 연결 후 제공됩니다.</p></div><div class="pr-card soft"><h4>다음 기술고도화</h4><ul><li>Hybrid RAG + 원문 페이지 citation</li><li>Claude API 기반 맞춤형 해석·추가질문</li><li>Multi-Respondent 대표/CTO/생산책임자 교차진단</li><li>재진단 Delta·Peer Benchmark·Gold Set 검증</li></ul></div></div><div class="pr-divider"></div><table class="pr-table"><thead><tr><th>검증항목</th><th>현재상태</th><th>정식서비스 전 요구사항</th></tr></thead><tbody><tr><td>내용타당도</td><td>POC</td><td>전문가 CVI/CVR</td></tr><tr><td>사용자 이해도</td><td>내부 QA</td><td>대표자 Cognitive Interview</td></tr><tr><td>문항 신뢰도</td><td>미검증</td><td>기업 Pilot·문항분석</td></tr><tr><td>로드맵 검색정확도</td><td>원문 색인 키워드 일치</td><td>Gold Set·Hit@K·NDCG·Citation Accuracy</td></tr><tr><td>점수 Calibration</td><td>POC 가중치</td><td>업종·규모별 데이터 기반 보정</td></tr></tbody></table><div class="pr-callout"><b>면책:</b> 본 보고서는 기업 내부 경영·기술개발 의사결정 지원을 목적으로 하며, 공인 기술평가·기술가치평가·법정 인증·투자 또는 정부지원 선정 가능성을 보증하지 않습니다.</div><div class="pr-source">Report ID ${reportId()} · Generated ${reportDate()} · App ${versionLabel()} · Assessment v${r.versions.assessment} · Question ${r.versions.question} · Scoring ${r.versions.scoring} · Roadmap KB ${r.versions.roadmapKb}</div>`,total);
  $('printReport').innerHTML=html;
}

function render(){seedInv();document.querySelectorAll(".section").forEach((e,i)=>e.classList.toggle("active",i===state.step));nav();basic();discovery();inv();diagnosis();evidence();if(state.step===5||state.results){result();buildPrintReport()}}
function saveState(){syncBasic();syncDiscovery();localStorage.setItem(STORAGE_KEY,JSON.stringify(state));alert("현재 상태를 저장했습니다.")}
function loadState(){try{let s=localStorage.getItem(STORAGE_KEY);if(s){let o=JSON.parse(s);state={...fresh(),...o,company:{...fresh().company,...o.company},discovery:{...fresh().discovery,...o.discovery}}}}catch(e){state=fresh()}}
function resetState(){if(confirm("현재 입력을 초기화할까요?")){localStorage.removeItem(STORAGE_KEY);state=fresh();render();navTo(0)}}
function printReport(){syncBasic();syncDiscovery();calc();result();buildPrintReport();setTimeout(()=>window.print(),60)}
function loadSample(){state=fresh();state.company={name:"샘플AI 제조솔루션",stage:"소기업",roadmapField:"스마트제조(특화)",bizType:"융합형(제조+SW/AI)",sectorDetail:"AI 기반 설비 예지보전",size:"20~49명",years:"4~7년",techKnow:"부분적으로 알고 있음",product:"설비 센서데이터와 AI를 이용해 이상징후를 탐지하고 고장 가능성을 예측하는 예지보전 솔루션",customer:"중소 제조기업의 생산·설비관리 담당자"};state.discovery={hardPart:"설비별 센서데이터 정규화와 이상패턴 탐지",automated:"설비 이상징후 탐지와 정비 우선순위 추천",data:"진동·온도·전류 센서데이터와 설비 이벤트 로그",external:"클라우드 인프라와 일부 LLM API",people:"CTO·AI 개발자·현장 엔지니어",validation:"2개 제조현장 PoC 및 내부 성능 테스트"};state.inventory=[{id:1,name:"설비센서 데이터 정규화",type:"데이터기술",ownership:"자체",status:"확정",critical:true,trl:6,confirmed:true},{id:2,name:"이상징후 탐지 모델",type:"AI/알고리즘",ownership:"혼합",status:"확정",critical:true,trl:6,confirmed:true},{id:3,name:"예지보전 플랫폼",type:"응용기술",ownership:"자체",status:"확정",critical:true,trl:7,confirmed:true},{id:4,name:"클라우드·LLM 연계",type:"통합기술",ownership:"외부",status:"대표진술",critical:false,trl:7,confirmed:true}];Object.assign(state.answers,{q1:5,q2:4,q3:3,q4:3,q5:3,q6:3,q7:3,q8:3,q9:2,q10:2,q11:2,q12:4,d1:4,d2:3,d5:3,d6:3,d7:2});[...CORE,...deepQs()].forEach(q=>state.evidence[q.id]=1);["q1","q2","q6"].forEach(k=>state.evidence[k]=3);["q3","q4","q12"].forEach(k=>state.evidence[k]=2);state.mode="deep";state.visited=[0,1,2,3,4,5];state.step=0;state.results=null;render();alert("샘플기업 데이터를 불러왔습니다.")}

Object.assign(window, {
  ans, applyExample, loadSample, makeInv, navTo, printReport, resetState, saveState, setEntry, setEv, setInv, setMode, toggleInv,
});

export function start() {
  loadState();
  render();
  // 원문 색인은 별도 파일로 비동기 로드 — 결과가 이미 있으면 로드 후 결과·보고서만 다시 그린다(입력 화면은 건드리지 않음)
  void loadRoadmapIndex().then(() => {
    if (state.results) {
      result();
      buildPrintReport();
    }
  });
}
